# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class error_box(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog  # save the Dialog object as an instance variable
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 264)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 180, 107, 42))
        self.pushButton.setStyleSheet("#pushButton{\n"
                                      "padding: 8px 16px;\n"
                                      "height: 42px;\n"
                                      "background: #1877F2;\n"

                                      "border-radius: 8px;\n"
                                      "color:white;\n"
                                      "font-size:14px;\n"
                                      "\n"
                                      "}\n"
                                      "\n"
                                      "#pushButton:hover{\n"
                                      "background: white;\n"
                                      "color: #1877F2;\n"
                                      "border:1px solid #1877f2;\n"

                                      "}\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 461, 49))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color:#1877F2;\n"
                                 "color:white;\n"
                                 "padding:15px;\n"
                                 "")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 281, 41))
        self.label_2.setStyleSheet("text-align:center;\n"
                                   "font-size:16px;\n"
                                   "")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.pushButton.clicked.connect(self.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Ok"))
        self.label.setText(_translate("Dialog", "QuizMaster"))
        self.label_2.setText(_translate(
            "Dialog", "something went wrong!!  Check again"))

    def close(self):
        self.Dialog.close()

    def set_text(self, text):
        self.label_2.setText(text)