# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import hashlib
from PyQt5 import QtCore, QtGui, QtWidgets
from connection import db_connection


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(657, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setStyleSheet("background-color: rgb(20, 79, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 90, 130, 29))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 251, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setStyleSheet("background-color:white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(40, 390, 251, 48))
        self.pushButton.setStyleSheet(
            "#pushButton{\n"
            "padding: 8px 16px;\n"
            "height: 42px;\n"
            "background: #1877F2;\n"
            "border-radius: 8px;\n"
            "color:white;\n"
            "font-size:14px;\n"
            "\n"
            "}\n"
            "\n"
            "#pushButton:hover{\n"
            "background: white;\n"
            "color: #1877F2;\n"
            "border:1px solid #1877f2;\n"
            "}\n"
            ""
        )
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(40, 170, 91, 16))
        self.label_6.setStyleSheet("color: #344054;")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(40, 120, 251, 42))
        self.lineEdit.setStyleSheet(
            "color:black;\n"
            "padding:10px;\n"
            "background: #FFFFFF;\n"
            "border: 1px solid #D0D5DD;\n"
            "border-radius: 4px;"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 190, 251, 40))
        self.lineEdit_2.setStyleSheet(
            "color:black;\n"
            "padding:10px;\n"
            "background: #FFFFFF;\n"
            "border: 1px solid #D0D5DD;\n"
            "border-radius: 4px;"
        )
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 100, 91, 16))
        self.label_5.setStyleSheet("color: #344054;")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:black;")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(40, 240, 91, 16))
        self.label_7.setStyleSheet("color: #344054;")
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 260, 251, 40))
        self.lineEdit_3.setStyleSheet(
            "color:black;\n"
            "padding:10px;\n"
            "background: #FFFFFF;\n"
            "border: 1px solid #D0D5DD;\n"
            "border-radius: 4px;"
        )
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(40, 310, 121, 16))
        self.label_8.setStyleSheet("color: #344054;")
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 330, 251, 40))
        self.lineEdit_4.setStyleSheet(
            "color:black;\n"
            "padding:10px;\n"
            "background: #FFFFFF;\n"
            "border: 1px solid #D0D5DD;\n"
            "border-radius: 4px;"
        )
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 657, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QuizMaster"))
        self.label_2.setText(
            _translate(
                "MainWindow", "Think fast, score high. The ultimate Quiz App experience"
            )
        )
        self.pushButton.setText(_translate("MainWindow", "Sign up"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter your id"))
        self.lineEdit_2.setPlaceholderText(
            _translate("MainWindow", "Enter your email address")
        )
        self.label_5.setText(_translate("MainWindow", "ID"))
        self.label_4.setText(_translate("MainWindow", "Sign up to get started"))
        self.label_7.setText(_translate("MainWindow", "Password"))
        self.lineEdit_3.setPlaceholderText(
            _translate("MainWindow", "Enter your password")
        )
        self.label_8.setText(_translate("MainWindow", "Confirm password "))
        self.lineEdit_4.setPlaceholderText(
            _translate("MainWindow", "Re-enter password")
        )

        self.pushButton.clicked.connect(self.reg_user)


    def reg_user(self):
        user_id = self.lineEdit.text()
        email = self.lineEdit_2.text()
        password = self.lineEdit_3.text()
        con_password = self.lineEdit_4.text()
        hash_obj = hashlib.md5()
        hash_obj.update(password.encode("utf-8"))
        hash_password = hash_obj.hexdigest()
        hash_obj_con = hashlib.md5()
        hash_obj_con.update(con_password.encode("utf-8"))
        hash_password_con = hash_obj_con.hexdigest()
        status='' 
        user_role = ''
        print('user_id',user_id)
        print('email',email)
        print('hash_password',hash_password)
        print('hash_password_con',hash_password_con)

        if hash_password == hash_password_con:
            cursor = db_connection.cursor()
            sql = "SELECT * FROM users WHERE user_id = %s;"
            cursor.execute(sql, (user_id))
            result = cursor.fetchone()
            print(result)
            # check if the result is not None (i.e., if user ID exists in the table)
            if result is not None:
                user_exists = True
            else:
                user_exists = False
                sql = "INSERT INTO users (user_id, email, password, con_password) VALUES (%s, %s, %s, %s,%s)"
                values = (user_id, password, email, status, user_role)

                # execute the INSERT statement with the values
                cursor.execute(sql, values)

                # commit the changes to the database
                db_connection.commit()

        else: 
            self.pushButton.setText("Browse")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
